all : mybairstow 1spline 2spline 3spline lsm second_lsm

mybairstow : mybairstow.c
	gcc -o mybairstow mybairstow.c -lm

1spline : 1spline.c
	gcc -o 1spline 1spline.c

2spline : 2spline.c
	gcc -o 2spline 2spline.c

3spline : 3spline.c
	gcc -o 3spline 3spline.c

lsm : lsm.c
	gcc -o lsm lsm.c

second_lsm : second_lsm.c
	gcc -o second_lsm second_lsm.c
