all : numerical_integration differential_equation  

numerical_integration : numerical_integration.c
	gcc -o numerical_integration numerical_integration.c -lm

differential_equation : differential_equation.c
	gcc -o differential_equation differential_equation.c -lm
