all : gauss pgauss ppgauss ppfgauss

gauss : gauss.c
	gcc -o gauss gauss.c -lm

pgauss : pgauss.c
	gcc -o pgauss pgauss.c -lm

ppgauss : ppgauss.c
	gcc -o ppgauss ppgauss.c -lm

ppfgauss : ppfgauss.c
	gcc -o ppfgauss ppfgauss.c -lm

