all : gj pgj ppgj ppfgj inverse ppinverse

gj : gj.c
	gcc -o gj gj.c -lm

pgj : pgj.c
	gcc -o pgj pgj.c -lm

ppgj : ppgj.c
	gcc -o ppgj ppgj.c -lm

ppfgj : ppfgj.c
	gcc -o ppfgj ppfgj.c -lm

inverse : inverse.c
	gcc -o inverse inverse.c -lm

ppinverse : ppinverse.c
	gcc -o ppinverse ppinverse.c -lm
